config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Booker::Application.routes.draw do  
  resources :images
  resources :supplements
  mount Payola::Engine => '/payola', as: :payola
  
  default_url_options :host => "lvh.me:3000"
 # default_url_options :host => "sshrsa.com:3000"
  resources :steps
  get '/records/history', to: 'records#history', as: :records_history
  #resources :records
  resources :versions, only: [] do
    member do
      patch :bringback  # <= and that
    end
  end
  
  resources :records do
    collection do 
      get :deleted # <= this
    end
    member do
     get :update_field, to: 'records#update_field' 
    end
    
    resources :versions, only: [:destroy] do
      member do
        get :diff, to: 'versions#diff'
        patch :rollback, to: 'versions#rollback'
      end
    end

    collection do
      get   :manage
      get   :drafts
      get   :awaiting_approvement
      get   :approved
      get   :approvement_request
      get   :accept_approvement
      get   :cancel_approvement
      # required for Sortable GUI server side actions
      post :rebuild
    end
  end
  resources :inputs
  resources :attachments
  resources :forms
  resources :former
  get "home", to: "pages#home", as: "home"  
  match "create_record", to: "records#create_record", as: "create_record", via: [:get, :post]
  match "import_csv", to: "records#import_csv", as: "import_csv", via: [:post]
  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  constraints(SubdomainPresent) do    
    root "pages#inside", as: :dashboard
    get "inside", to: "pages#inside", as: "inside"    
    get "activity", to: "pages#activity", as: "activity"    
    
    post 'qrc/disable_otp'
    post 'qrc/enable_otp'

    namespace :admin do
      root "base#index"
      post "users/invite_user", as: 'invite_user'
      resources :users
      get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
      get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
      get "forms/dashboard", to: "forms#dashboard", as: "forms_dashboard"
      resources :posts
      resources :forms
      resources :inputs      
    end
  end

  constraints(SubdomainBlank) do
    post 'pages/require_subdomain'
    root "pages#home"
    resources :accounts, only: [:new, :create]
  end

end

app/models/supplement.rb
require 'rmagick'
class Supplement < ActiveRecord::Base
  # after_create :split_to_images

  has_many :images
  has_attached_file :source_pdf,
                    storage: :dropbox,
                    dropbox_credentials: Rails.root.join('config/dropbox.yml'),
                    dropbox_options: {}

  do_not_validate_attachment_file_type :source_pdf
  extend FriendlyId
  friendly_id :title, use: :slugged
  # private

  def split_to_images
    source_pdf_url = source_pdf.url
    pdf = Magick::ImageList.new(source_pdf_url)
    pdf.each_with_index do |magick_image, index|
      begin
        file = Tempfile.create ["_#{index}_", '.jpg']
        magick_image.write(file.path)
        images.create(file: file)
      end
    end
    end

  def get_annotations(original_url)
    client = Parse.create(application_id: 'TwYltjxRhqIs9Cdv7dV4kQD1iiNzUPhitFLoTThh',
                          api_key: 'D3OdPMjEQDcY9801vV89AfHGphbHeTQzLIXj2PeK')
    annotations = client.query('Annotation').eq('context', original_url).get
    annotations
  end
end

app/controllers/supplements_controller.rb
class SupplementsController < ApplicationController
  before_action :set_supplement, only: [:show, :edit, :update, :destroy]

  # GET /supplements
  # GET /supplements.json
  def index
    @supplements = Supplement.all
  end

  # GET /supplements/1
  # GET /supplements/1.json
  def show
    @annotations = @supplement.get_annotations(request.original_url.gsub('.pdf', ''))
    respond_to do |format|
      format.html
      format.pdf { render_supplement_report(@supplement, @annotations) }
    end
  end

  # GET /supplements/new
  def new
    @supplement = Supplement.new
  end

  # GET /supplements/1/edit
  def edit
  end

  # POST /supplements
  # POST /supplements.json
  def create
    @supplement = Supplement.new(supplement_params)

    respond_to do |format|
      if @supplement.save
        FileWorker.perform_in(2.minutes, @supplement.id)
        format.html { redirect_to @supplement, notice: 'Supplement was successfully created.' }
        format.json { render :show, status: :created, location: @supplement }
      else
        format.html { render :new }
        format.json { render json: @supplement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplements/1
  # PATCH/PUT /supplements/1.json
  def update
    respond_to do |format|
      if @supplement.update(supplement_params)
        format.html { redirect_to @supplement, notice: 'Supplement was successfully updated.' }
        format.json { render :show, status: :ok, location: @supplement }
      else
        format.html { render :edit }
        format.json { render json: @supplement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplements/1
  # DELETE /supplements/1.json
  def destroy
    @supplement.destroy
    respond_to do |format|
      format.html { redirect_to supplements_url, notice: 'Supplement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_supplement
    @supplement = Supplement.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def supplement_params
    params.require(:supplement).permit(:title, :slug, :description, :images_count, :source_pdf)
  end

  def render_supplement_report(supplement, annotations)
    report = ThinReports::Report.new
    report.use_layout "#{Rails.root}/app/reports/supplement_report", default: true
    report.use_layout "#{Rails.root}/app/reports/annotations", id: :ann_list
    supplement.images.each do |image|
      report.start_new_page do
        item(:title).value(supplement.title)
        list(:images).add_row do |row|
          row.item(:image).src(open(image.file.url))
        end
      end
    end
    report.start_new_page layout: :ann_list do
      annotations.each do |annotation|
        list(:annotations).add_row do |row|
          image = MiniMagick::Image.open(annotation['src'])
          dimension_height  = image.height
          dimension_width = image.width
          geometry = annotation['shapes'].first['geometry']
          geometry_string = "#{(geometry['width'] * dimension_width).to_i}x#{(geometry['height'] * dimension_height).to_i}+#{(geometry['x'] * dimension_width).to_i}+#{(geometry['y'] * dimension_height).to_i}"
          image = image.crop(geometry_string)
          file = File.open(image.path)
          row.item(:image).src(file)
          row.item(:annotation_text).value(annotation['text'])
        end
      end
    end
    send_data report.generate, filename: 'supplement_report.pdf',
                               type: 'application/pdf',
                               disposition: 'attachment'
  end
end

app/views/supplements/_form.html.erb
<%= simple_form_for(@supplement) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.label :source_pdf %>
    <p><%= @supplement.source_pdf.exists? ? link_to(@supplement.source_pdf_file_name, "#{@supplement.source_pdf.url}?dl=1") : "-" %></p>
    <%= f.file_field :source_pdf,  class: " " %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/supplements/edit.html.erb
<h1>Editing Supplement</h1>

<%= render 'form' %>

<%= link_to 'Show', @supplement %> |
<%= link_to 'Back', supplements_path %>

app/views/supplements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Supplements</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Description</th>
      <th>Images count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @supplements.each do |supplement| %>
      <tr>
        <td><%= supplement.title %></td>
        <td><%= supplement.slug %></td>
        <td><%= supplement.description %></td>
        <td><%= supplement.images_count %></td>
        <td><%= link_to 'Show', supplement %></td>
        <td><%= link_to 'Edit', edit_supplement_path(supplement) %></td>
        <td><%= link_to 'Destroy', supplement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supplement', new_supplement_path %>

app/views/supplements/new.html.erb
<h1>New Supplement</h1>

<%= render 'form' %>

<%= link_to 'Back', supplements_path %>

app/views/supplements/show.html.erb
<!--p id="notice"><%= notice %></p-->


<h3 class="text-info"> <strong>Title:</strong>
  <%= @supplement.title %>
</h3>
<p>
  <strong>Source pdf:</strong>
  <%= link_to @supplement.source_pdf_file_name, @supplement.source_pdf.url  %>
</p>

<p>
  <strong>Description:</strong>
  <%= @supplement.description %>
</p>

<p>
  <strong>Images count:</strong>
  <%= @supplement.images_count %>
  </p>
  <%= link_to "Download (*.pdf)", supplement_path(@supplement, :format => "pdf"), :class=> "btn btn-info"%>
<% @supplement.images.each do |image| %>
  <%= image_tag image.file.url, :class => "annotatable" %>
<% end %>
<!-- width: 930px   height: 698   -->
<%- @annotations.each do |annotation| %>
  <%- 
    
    image = MiniMagick::Image.open(annotation['src'])
    geometry = annotation["shapes"].first["geometry"]
    height = image.height * geometry["height"]
    width = image.width * geometry["width"]
    x_left = image.width * geometry["x"]#  * 100 
    y_top = image.height * geometry["y"]# * 100
    x_right = x_left + width
    y_bottom = y_top + height
  %>
 
 <style>
a#image {
  display: block;
  
   background-repeat: no-repeat;
   
  
}


</style>
<hr />
<div class="row">
  <div class="col-md-4 ">
    <a id="image" class="well" href="http://example.com" style="background-position: -<%= x_left %>px -<%= y_top %>px;   width: <%= width %>px; height: <%= height %>px; background-image: url(<%=annotation['src'] %>)">
    </a>
  </div>
  <div class="col-md-8">
    <div class="well">
      <p class="text-info"><%= annotation["text"]%></p>
      <p class="text-mutted"><%= time_ago_in_words(annotation["createdAt"])%> ago</p>
    </div>
  </div>
  </div>
<% end %>

<%= link_to 'Edit', edit_supplement_path(@supplement), :class => "btn btn-primary" %> |
<%= link_to 'Back', supplements_path , :class => "btn btn-primary"%>