config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Booker::Application.routes.draw do  
  resources :images
  resources :supplements
  mount Payola::Engine => '/payola', as: :payola
  
  default_url_options :host => "lvh.me:3000"
 # default_url_options :host => "sshrsa.com:3000"
  resources :steps
  get '/records/history', to: 'records#history', as: :records_history
  #resources :records
  resources :versions, only: [] do
    member do
      patch :bringback  # <= and that
    end
  end
  
  resources :records do
    collection do 
      get :deleted # <= this
    end
    member do
     get :update_field, to: 'records#update_field' 
    end
    
    resources :versions, only: [:destroy] do
      member do
        get :diff, to: 'versions#diff'
        patch :rollback, to: 'versions#rollback'
      end
    end

    collection do
      get   :manage
      get   :drafts
      get   :awaiting_approvement
      get   :approved
      get   :approvement_request
      get   :accept_approvement
      get   :cancel_approvement
      # required for Sortable GUI server side actions
      post :rebuild
    end
  end
  resources :inputs
  resources :attachments
  resources :forms
  resources :former
  get "home", to: "pages#home", as: "home"  
  match "create_record", to: "records#create_record", as: "create_record", via: [:get, :post]
  match "import_csv", to: "records#import_csv", as: "import_csv", via: [:post]
  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  constraints(SubdomainPresent) do    
    root "pages#inside", as: :dashboard
    get "inside", to: "pages#inside", as: "inside"    
    get "activity", to: "pages#activity", as: "activity"    
    
    post 'qrc/disable_otp'
    post 'qrc/enable_otp'

    namespace :admin do
      root "base#index"
      post "users/invite_user", as: 'invite_user'
      resources :users
      get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
      get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
      get "forms/dashboard", to: "forms#dashboard", as: "forms_dashboard"
      resources :posts
      resources :forms
      resources :inputs      
    end
  end

  constraints(SubdomainBlank) do
    post 'pages/require_subdomain'
    root "pages#home"
    resources :accounts, only: [:new, :create]
  end

end

app/controllers/former_controller.rb
require 'open3'
class FormerController < ApplicationController
  before_action :authenticate_user!

  include Wicked::Wizard
  before_action :set_steps
  before_action :setup_wizard
  before_action :set_record_id

  def show
    @record = Record.includes(:form).find(params[:record_id])
    @form = @record.form
    if step != :finish
      @step_object = @form.steps.where(number: step.to_s.gsub('step', '').to_i).first
    end
    render_wizard
  end

  def update
    @record = Record.includes(:user).find(params[:record][:id])

    current_step_index = (wizard_steps.index(step) + 1)
    if @record.extras
      @record.extras['current_step'] = next_step
      @record.extras['progress'] = "#{current_step_index.to_f.send(:/, wizard_steps.size).send(:*, 100).round(0)}%"
    else
      @record.extras = { 'current_step' => next_step, 'progress' => "#{(current_step_index).to_f.send(:/, wizard_steps.size).send(:*, 100)}%" }
    end

    if params[:record][:signature]
      instructions = JSON.parse(params[:record][:signature]).map { |h| "line #{h['mx'].to_i},#{h['my'].to_i} #{h['lx'].to_i},#{h['ly'].to_i}" } * ' '
      tempfile = Tempfile.new(['signature', '.png'])
      Open3.popen3("convert -size 698x300 xc:transparent -stroke blue -draw @- #{tempfile.path}") do |input, _output, _error|
        input.puts instructions
      end
      @record.signature = tempfile
    end
    if @record.data
      @record.data = @record.data.merge(params[:record][:data]) if params[:record][:data]
    else
      @record.data = params[:record][:data] if params[:record][:data]
    end
    @record.save
    if params[:record][:relations_attributes] || params[:record][:locations_attributes]
      @record.update(record_params)
    end
    redirect_to wizard_path(@next_step, record_id: @record.id)
  end

  def finish_wizard_path
  end

  private

  def redirect_to_finish_wizard
    redirect_to root_url, notice: 'Thanks for signing up.'
  end

  def set_record_id
    session[:record_id] = params[:record_id] if params[:record_id]
  end

  def set_steps
    session[:record_id] = params[:record_id] if params[:record_id]
    @form = Record.find(session[:record_id]).form
    form_steps = @form.steps.map { |s| "step#{s.number}" }
    form_steps << 'signature' if @form.signature_required
    form_steps << 'attachments' if @form.file_upload
    form_steps << 'finish'
    self.steps = form_steps
  end

  def record_params
    params.require(:record).permit!
  end
end

app/views/former/_form.html.erb
<%= nested_form_for(@record, :url => wizard_path, :method => :put) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.hidden_field :form_id %>
    <%= f.hidden_field :id %>
  </div>
  <%= f.fields_for :data, OpenStruct.new(f.object.data) do |p| %>
  <%- @form.steps.where(:number => step.to_s.gsub('step','').to_i).first.inputs.each do |i| %>
    <div class="form-group">
      <%= p.label i.name %>
        <div class="row">
          <div class="col-xs-12 ">
            <% case i.control  %>
            <% when 'text_field' %>
              <%= p.text_field i.name, class: "form-control monospaced-control required", :required =>true %>
            <% when 'text_area' %>
              <%= p.text_area i.name, class: "form-control monospaced-control required" %>
            <% when 'date' %>
              <%= p.date_field i.name, class: "form-control monospaced-control" %>
            <% when 'phone' %>
              <%= p.telephone_field i.name, class: "form-control monospaced-control" %>
            
            <% when 'email' %>
              <%= p.email_field i.name, class: "form-control monospaced-control" %>
            
            <% when 'select' %>
              <%= p.select i.name, i.field_values.collect {|p| [ p.value, p.id ] } ,{include_blank: true }, {:class=>"form-control"}  %>
            
            <% when 'radio' %>
              <% i.field_values.each do |field_value| %>
                 <%= p.radio_button i.name, field_value.value %>
                 <%= p.label i.name, field_value.value %>
              <% end %>
            
            <% when 'checkboxes' %>
              <% i.field_values.each do |field_value| %>
                <%= p.check_box "#{i.name[field_value.value]}" %>
                 <%= p.label i.name, field_value.value %>
               <% end %>
             
            <% else %>
              <%= p.text_field i.name, class: "form-control monospaced-control" %>
            <% end %>  
          </div>
        </div>
    </div>
  <% end %>
<% end %>

  
   
  <div class="actions">
    <%= f.submit "Next", :class=>"btn btn-sm btn-primary" %>
  </div>
<% end %>

app/views/former/_relation_fields.html.erb
<div class="form-group form-group-sm ">
  <div class="row">
    <div class="col-md-6 col-md-offset-1">
      
      <%= f.association :related_record, collection: Record.by_form(form_type.to_i).map {|r| [r.data.to_s, r.id]} , label: false, input_html: { class: 'form-control input-xs' },class: "btn btn-xs form-control monospaced-control"%>
      
    </div>
    <div class="col-xs-3">
      <%= f.link_to_remove "Remove", :class=>"btn btn-xs btn-danger" %>
    </div>
  </div>
  <br>
</div>

app/views/former/_simple_form.html.erb
<script>
  $(document).ready(function() {
    $(".phone").mask('(999) 999-9999');
      });
</script>    
<%- @record.locations.build %>
<%= simple_nested_form_for @record , :url => wizard_path, :method=> :put  ,html: { :multipart => true, class: 'former-form form-horizontal button_to' },  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>
  
   <%= tutorial_progress_bar %> 
  
<div class="step-content">
 
  <%-form_step =  @form.steps.where(:number => step.to_s.gsub('step','').to_i).first %>
  <div class="row">
  <div class="col-md-6 col-md-offset-1">
  <p class="text-primary "><%= form_step.title %> </p>
  <%= f.error_notification %>
  <%= f.hidden_field :form_id %>
  <%= f.hidden_field :id %>
  <%= f.simple_fields_for :data, OpenStruct.new(f.object.data) do |p| %>
    <%- form_step.inputs.each do |i| %>
      <% case i.control  %>
            <% when 'text_area' %>
              <%= p.input i.slug, :label=> i.name, label_html: { 'data-toggle': 'tooltip', 'title': i.help },  wrapper_html: { } %>
            <% when 'date' %>
              <%= p.input i.slug, :label=> i.name, as: :string, :required => i.required, label_html: { 'data-toggle': 'tooltip', 'title': i.help }, :input_html=> { :class=>"form-control" ,:data => {:provide => 'datepicker'} }  %>
            <% when 'phone' %>
              <%= p.input i.slug, :label=> i.name, :as => :tel, :required => i.required, label_html: { 'data-toggle': 'tooltip', 'title': i.help }, :input_html => { :data => {:toggle => "popover",:placement => "top", :trigger => "focus", :content => "#{i.help}"}, :class=>"phone", :maxlength => 14, :"data-mask" => "999-999-9999" }  %>
            <% when 'email' %>
              <%= p.input i.slug, :label=> i.name, :as => :email,  :required => i.required , label_html: { 'data-toggle': 'tooltip', 'title': i.help }, :input_html => { :data => {:toggle => "popover",:placement => "top", :trigger => "focus", :content => "#{i.help}"}} %>
            <% when 'select' %>
              <%= p.input i.slug, :label=> i.name, :required => i.required, label_html: { 'data-toggle': 'tooltip', 'title': i.help }, collection: i.field_values.map {|v|  v.value },:input_html => { :data => {:toggle => "popover",:placement => "top", :trigger => "focus", :content => "#{i.help}"}} %>
            <% when 'location' %>
                <div id="address-panel">
                  <%= f.simple_fields_for :locations do |location| %>
                    <%= location.input :full_address , :input_html => {:class=>"address typeahead"}%>  
                  <% end %>
                  <pre id="response" style="display:none;"> </pre>
                </div>
                <div id="map" class="well" style="width:200px; height: 200px; position: relative; overflow: hidden; transform: translateZ(0px) translateZ(0px); margin-right: 0px; margin-left: 3px; left: 130px; background-color: rgb(229, 227, 223);"></div>
                <div style="clear:both"></div>
                <!--tiles start-->
                <script> 
                  $(document ).ready(function() {
                     $( function() {
                  // instantiate the addressPicker suggestion engine (based on bloodhound)
                  var addressPicker = new AddressPicker({map: {id: "#map", displayMarker: true}, zoomForLocation: 18, draggable: true, reverseGeocoding: true, autocompleteService: {types: ['geocode'], componentRestrictions: {country: 'US'}}});
                  // instantiate the typeahead UI
                  $('.address').typeahead(null, {
                    displayKey: 'description',
                    source: addressPicker.ttAdapter()
                  });
                  addressPicker.bindDefaultTypeaheadEvent($('.address'))
                  $(addressPicker).on('addresspicker:selected', function (event, result) {
                    html = ["Address: " + result.address()]
                    html.push("Latitude: " + result.lat())
                    html.push("Longitude: " + result.lng())
                    html.push("Long names:")
                    $('.location_lat').val(result.lat());
                    $('.location_lng').val(result.lng());
                    result.addressTypes().forEach(function(type) {
                      html.push("  " + type + ": " + result.nameForType(type))
                    })
                    html.push("Short names:")
                    result.addressTypes().forEach(function(type) {
                      html.push("  " + type + ": " + result.nameForType(type, true))
                    })
                    $('#response').html( html.join('\n'))
                  })
                })

                });
                </script>  
            <% when 'tags' %>
              <%#= p.select i.name, i.field_values.collect {|p| [ p.id, p.value ] } ,{include_blank: true }, {:class=>"form-control tags" ,'data-role'=>'tagsinput', :multiple => true}  %>
              <%= p.input i.slug, :label=> i.name,  :required => i.required, label_html: { 'data-toggle': 'tooltip', 'title': i.help },  :input_html => { :class=>"form-control", :data => {:toggle => "popover",:placement => "top", :role => "tagsinput", :trigger => "focus",  :content => "#{i.help}"}}, wrapper_html: {}  %>
            <% when 'radio' %>
              <%= p.input i.slug, :label=> i.name, :required => i.required, label_html: { 'data-toggle': 'tooltip', 'title': i.help }, collection: i.field_values.map {|v| v.value}, as: :radio_buttons,:input_html => { :data => {:toggle => "popover",:placement => "top", :trigger => "focus", :content => "#{i.help}"}} %>
            <% when 'relation' %>
              <div class="row">
                <div class="panel panel-default ">
                  <div class="panel-heading">Related records: </div>
                  <div class="panel-body">
                    <%= f.simple_fields_for :relations do |relations| %>
                        <%= render 'relation_fields',  { f: relations, form_type: i.data['relation'] }  %>
                    <% end %>
                    <p>
                      <%= f.link_to_add(:relations, :class=>'btn btn-xs btn-info ') do %>
                        <i class="fa  fa-plus-circle"></i> add relation
                      <% end %>
                    </p>
                  </div>
                </div>
              </div>
            <% when 'checkboxes' %>
              <% if @record.data and @record.data[i.name] %>
                <%= p.input i.slug, :label=> i.name , label_html: { 'data-toggle': 'tooltip', 'title': i.help }, :required => i.required, collection: i.field_values.map{|v| v.value }, as: :check_boxes,  :checked =>  JSON.parse(@record.data[i.name]),:input_html => { :data => {:toggle => "popover",:placement => "top", :trigger => "focus", :content => "#{i.help}"}}  %>
              <% else %>
                <%= p.input i.slug, :label=> i.name , label_html: { 'data-toggle': 'tooltip', 'title': i.help }, :required => i.required, collection: i.field_values.map{|v| v.value }, as: :check_boxes,:input_html => { :data => {:toggle => "popover",:placement => "top", :trigger => "focus", :content => "#{i.help}"}}  %>
              <% end%>
            <% else %>
              <%= p.input i.slug, :label=> i.name, :required => i.required, label_html: { 'data-toggle': 'tooltip', 'title': i.help }, :input_html => { :data => {:toggle => "popover",:placement => "top", :trigger => "focus", :content => "#{i.help}"}}, wrapper_html: { class: ""}  %>
            <% end %>
            <!-- HTML to write -->
    <% end %>
  <% end %>
  </div>
  </div>
  <%#= f.button :submit %>
<% end %>
<br>
</div>
 <%- @form.steps.where(:number => step.to_s.gsub('step','').to_i).first.slave_forms.each do |slave_form| %>
   <div class="panel panel-info">
    <div class="panel-body">
          <table class="table  table-bordered table-condensed table-hover">
            <thead>
              <tr>
                <th> Title </th>
                <%- slave_form.column_headers_slave.each do |header| %>
                  <th><%= header %></th>
                <% end %>
                <th> </th>
              </tr>
            </thead>
            <tbody>
              <% @record.slave_records.where(:form_id => slave_form.id).each do |slave_record| %>
                <tr>
                  <td> <%= slave_record.title %></td>
                  <% slave_form.column_headers_slave.each do |header| %>
                    <td><%= slave_record.data[header] %></td>
                  <% end %>
                  <td style="width: 5%;"><%= link_to 'Destroy', slave_record, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-xs btn-danger" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="panel-footer">
          <%= link_to "Add #{slave_form.name}", new_record_path(:master_record_id => @record.id, :form_id => slave_form.id ), data: { modal: true }, :class=>"go-btn btn btn-info btn-xs" %>
        </div>
        </div>
        <% end %>

app/views/former/_step.html.erb
 <div class="panel panel-success">    
  <div class="panel-heading">
    <h3 class="panel-title">Fill the form</h3>
  </div>
  <div class="panel-body">      
    <section class="fuelux">
      <%= render 'simple_form' %>
    </section>
  </div>
</div>


<%= stylesheet_link_tag "main.css"%>

app/views/former/admin_signature.html.erb
<%= content_for :head do %>

<script>
    $(document).ready(function(){           
     $('.signature_form').signaturePad({ drawOnly: true, lineTop: 190, validateFields: false})
  });
  </script>
<% end %>
<div class="panel panel-default">    
    <div class="panel-body">      


<%= nested_form_for(@record, :url => wizard_path, :method => :put, :html => {:multipart => true, :class=>"signature_form" }) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <%= tutorial_progress_bar %>
    <hr>
    <div class="field">
    <%= f.hidden_field :form_id %>
    <%= f.hidden_field :id %>
  </div>
  <div class= "well sig sigWrapper">
    <canvas class= "pad" width="698" height="300">
        <%= f.hidden_field :signature, :value => nil, :class => 'output' %>
      </canvas>
      </div>
      
  <ul class="sigNav">
    <li class="clearButton"><a href="#clear" class="btn btn-default">Clear Signature Pad</a></li>
  </ul>
  <div class="actions">
    <%#= f.submit "Next", :class=>"btn btn-sm btn-primary" %>
  </div>
<% end %>

    </div>
</div>
<%= stylesheet_link_tag "main.css"%>

app/views/former/attachments.html.erb
<div class="panel panel-success">    
  <div class="panel-heading">
    <h3 class="panel-title">Attachments</h3>
  </div>
  <div class="panel-body">      
    <section class="fuelux">
  <%= nested_form_for(@record, :url => wizard_path, :method => :put, :html => {:multipart => true, :class=>"signature_form" }) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <%= tutorial_progress_bar %>
    <hr>
    <div class="field">
    <%= f.hidden_field :form_id %>
    <%= f.hidden_field :id %>
  </div>
 
  <div class="actions">
    <%#= f.submit "Next", :class=>"btn btn-sm btn-primary" %>
  </div>
<% end %>
  
    <div class="well">
      <%- @attachment = @record.attachments.new %>
      <%= form_for(@attachment,:url => attachments_path(@attachment), html: { multipart: true,:method => :post, class: "dropzone"}) do |f|  %>
        <%= f.hidden_field :record_id %>
        <div class="fallback">
        <%= f.file_field :upfile %><br>
        <%= f.submit "Upload" %>
      </div>
<% end %>
</div>
   
    </section>
  </div>
</div>

app/views/former/signature.html.erb
<%= content_for :head do %>

<script>
    $(document).ready(function(){           
     $('.signature_form').signaturePad({ drawOnly: true, lineTop: 190, validateFields: false})
  });
  </script>
<% end %>
<div class="panel panel-default">    
    <div class="panel-body">      


<%= nested_form_for(@record, :url => wizard_path, :method => :put, :html => {:multipart => true, :class=>"signature_form" }) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <%= tutorial_progress_bar %>
    <hr>
    <div class="field">
    <%= f.hidden_field :form_id %>
    <%= f.hidden_field :id %>
  </div>
  <div class= "well sig sigWrapper">
    <canvas class= "pad" width="698" height="300">
        <%= f.hidden_field :signature, :value => nil, :class => 'output' %>
      </canvas>
      </div>
      
  <ul class="sigNav">
    <li class="clearButton"><a href="#clear" class="btn btn-default">Clear Signature Pad</a></li>
  </ul>
  <div class="actions">
    <%#= f.submit "Next", :class=>"btn btn-sm btn-primary" %>
  </div>
<% end %>

    </div>
</div>
<%= stylesheet_link_tag "main.css"%>

app/views/former/step1.html.erb
<%= render 'step' %>

<%#= link_to 'Back', records_path %>

app/views/former/step2.html.erb
<%= render 'step' %>

<%#= link_to 'Back', records_path %>

app/views/former/step3.html.erb
<%= render 'step' %>

<%#= link_to 'Back', records_path %>

app/views/former/step4.html.erb
<%= render 'step' %>

<%#= link_to 'Back', records_path %>

app/views/former/step5.html.erb
<%= render 'step' %>

<%#= link_to 'Back', records_path %>

app/views/former/step6.html.erb
<%= render 'step' %>

<%#= link_to 'Back', records_path %>

app/views/former/step7.html.erb
<%= render 'step' %>

<%#= link_to 'Back', records_path %>