config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Booker::Application.routes.draw do  
  resources :images
  resources :supplements
  mount Payola::Engine => '/payola', as: :payola
  
  default_url_options :host => "lvh.me:3000"
 # default_url_options :host => "sshrsa.com:3000"
  resources :steps
  get '/records/history', to: 'records#history', as: :records_history
  #resources :records
  resources :versions, only: [] do
    member do
      patch :bringback  # <= and that
    end
  end
  
  resources :records do
    collection do 
      get :deleted # <= this
    end
    member do
     get :update_field, to: 'records#update_field' 
    end
    
    resources :versions, only: [:destroy] do
      member do
        get :diff, to: 'versions#diff'
        patch :rollback, to: 'versions#rollback'
      end
    end

    collection do
      get   :manage
      get   :drafts
      get   :awaiting_approvement
      get   :approved
      get   :approvement_request
      get   :accept_approvement
      get   :cancel_approvement
      # required for Sortable GUI server side actions
      post :rebuild
    end
  end
  resources :inputs
  resources :attachments
  resources :forms
  resources :former
  get "home", to: "pages#home", as: "home"  
  match "create_record", to: "records#create_record", as: "create_record", via: [:get, :post]
  match "import_csv", to: "records#import_csv", as: "import_csv", via: [:post]
  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  constraints(SubdomainPresent) do    
    root "pages#inside", as: :dashboard
    get "inside", to: "pages#inside", as: "inside"    
    get "activity", to: "pages#activity", as: "activity"    
    
    post 'qrc/disable_otp'
    post 'qrc/enable_otp'

    namespace :admin do
      root "base#index"
      post "users/invite_user", as: 'invite_user'
      resources :users
      get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
      get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
      get "forms/dashboard", to: "forms#dashboard", as: "forms_dashboard"
      resources :posts
      resources :forms
      resources :inputs      
    end
  end

  constraints(SubdomainBlank) do
    post 'pages/require_subdomain'
    root "pages#home"
    resources :accounts, only: [:new, :create]
  end

end

app/models/record.rb
class Record < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  # default_scope { order('created_at DESC') }
  before_create :add_data
  scope :by_form, -> (form) { where(form_id: form) }
  has_many :locations, as: :mapable
  acts_as_nested_set order_column: :lft
  include TheSortableTree::Scopes

  store_accessor :data

  has_attached_file :signature,
                    storage: :dropbox,
                    dropbox_credentials: Rails.root.join('config/dropbox.yml'),
                    dropbox_options: {}

  has_attached_file :admin_signature,
                    storage: :dropbox,
                    dropbox_credentials: Rails.root.join('config/dropbox.yml'),
                    dropbox_options: {}
  validates_attachment :signature, 
                content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif'] },
                :default_url => "/image-not-available"
  validates_attachment :admin_signature, content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif'] }

  RECORD_STATUSES = %w(draft awaiting approved)

  scope :drafts, -> { where(master_record_id: nil, status: 'draft') }
  scope :awaiting_response, -> { where(master_record_id: nil, status: 'awaiting') }
  scope :approved, -> { where(master_record_id: nil, status: 'approved') }

  has_many :relations, foreign_key: 'record_id', class_name: 'Relation'
  has_many :related_records, through: :relations
  has_many :slave_records, class_name: 'Record', foreign_key: 'master_record_id'
  belongs_to :master_record, class_name: 'Record'

  belongs_to :form
  counter_culture :form
  counter_culture [:form, :account]
  belongs_to :user
  has_many :attachments, dependent: :destroy

  accepts_nested_attributes_for :attachments, allow_destroy: true
  accepts_nested_attributes_for :relations, allow_destroy: true
  accepts_nested_attributes_for :related_records, allow_destroy: true
  accepts_nested_attributes_for :locations, allow_destroy: true

  has_paper_trail only: [:data, :status]

  include PublicActivity::Model
  tracked owner: proc { |controller, _model| controller.current_user ? controller.current_user : nil }
  # return array of data hashes
  def data_fields
    data.to_hash
  rescue
    {}
  end
 
  def public_title
    "#{id} #{form.name}"
  end
  
  def load_layout
    record = self
    temp_layout = Tempfile.new(['layout', '.tlf'])
    template_url = record.form.template.url
    remote_data = open(template_url).read
    temp_layout.write(remote_data)
    temp_layout.close
    temp_layout
  end
  
  def report
    record = self
    temp_layout = Tempfile.new(['layout', '.tlf'])
    template_url = record.form.template.url
    remote_data = open(template_url).read
    temp_layout.write(remote_data)
    temp_layout.close
    qrcode = Tempfile.new(['qrcode', '.png'])
    qrcode.write(RQRCode::QRCode.new(edit_record_path(self)).as_png)
    qrcode.close
    report = ThinReports::Report.new layout: temp_layout.path
      report.start_new_page do
        item(:record_id).value(record.id) rescue nil  
        if record.signature.exists?
          item(:signature).src(open(record.signature.url)) rescue nil
        end
        item(:qr_code).src(qrcode.path) rescue nil
        record.data.each_pair do |key,value|  
            item(key).value(value) rescue nil
        end
        record.slave_records.each do |child|
          list.add_row do |row|
            row.item(:id).value(child.id) rescue nil
            row.item(:data).value(child.data.to_s) rescue nil
            child.data.each_pair do |key,value|  
              row.item(key).value(value) rescue nil
            end
          end
        end
    end
    report
  end
   
  private

  def add_data
    self.data = Hash.new unless data
    self.status = 'draft'
  end

  def self.ransackable_scopes(_auth_object = nil)
    [:drafts, :awaiting_response, :approved]
  end
  end

app/controllers/records_controller.rb
require 'open-uri'
require 'open3'
class RecordsController < ApplicationController
  include TheSortableTreeController::ExpandNode
  include TheSortableTreeController::Rebuild
  load_and_authorize_resource param_method: :record_params, except: [:drafts, :approved, :awaiting_approvement]
  respond_to :html,  :json
  before_action do
  end
  before_action :authenticate_user!
  before_action :set_record, only: [:show, :edit, :update, :destroy, :sample_layout]

  def manage
    @records = Record.nested_set.select('id, title,  parent_id').all
  end

  def nested_options
    @records = Record.nested_set.select('id, title, parent_id').limit(15)
  end

  def node_manage
    @root = Record.root
    @records = @root.self_and_descendants.nested_set.select('id, title, parent_id').limit(15)
    render template: 'records/manage'
  end

  def expand
    @records = Record.nested_set.roots.select('id, title, parent_id')
  end

  # GET /records
  # GET /records.json
  def index
    @q = Record.ransack(params[:q])
    @records = @q.result.includes(:form, :user).page(params[:page])
  end

  def approved
    @q = Record.ransack(params[:q], approved: true)
    @records = @q.result.approved.includes(:form, :user).page(params[:page])
    render :index
  end

  def drafts
    @q = Record.ransack(params[:q], approved: true)
    @records = @q.result.drafts.includes(:form, :user).page(params[:page])
    render :index
  end

  def awaiting_approvement
    @q = Record.ransack(params[:q])
    @records = @q.result.awaiting_response.includes(:form, :user).page(params[:page])
    render :index
  end

  def accept_approvement
    record = Record.find(params[:record_id])
    record.update(status: 'approved')
    if request.xhr?
      render :json => {:status => 'ok'}
    else
      redirect_to approved_records_path
    end
  end

  def cancel_approvement
    record = Record.find(params[:record_id])
    record.update(status: 'draft')
    if request.xhr?
      render :json => {:status => 'ok'}
    else
      redirect_to drafts_records_path
    end
  end

  def approvement_request
    record = Record.find(params[:record_id])
    record.update(status: 'awaiting')
    redirect_to awaiting_approvement_records_path
  end

  # GET /records/1
  # GET /records/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf { render_record_report(@record) }
    end
  end
  
  # GET /records/new
  def new
    @record = Record.new
    @record.data = {}
    if params[:form_id]
      @form = Form.find(params[:form_id])
    else
      @form = Form.first
    end
    @record.master_record_id = params[:master_record_id] if params[:master_record_id]
    @record.form = @form
    respond_modal_with @record
  end

  # GET /records/1/edit
  def edit
    @form = Form.all[0]
    add_breadcrumb "##{@record.id}", record_path(@record) # , :only => [:edit, :view, :new]
    add_breadcrumb 'Edit', edit_record_path(@record)
  end

  def create_record
    if params.key?(:account_id)
      account = Account.find(params[:account_id])
      Apartment::Tenant.switch(account.subdomain)
    end
    @record = current_user.records.create(form_id: params[:form_id])
    @record.attachments.new
    redirect_to former_path(:step1, record_id: @record.id)
  end

  # POST /records
  # POST /records.json
  def create
    @record = current_user.records.create(record_params)
    respond_modal_with @record, location: request.referer
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    if params[:record][:admin_signature]
      instructions = JSON.parse(params[:record][:admin_signature]).map { |h| "line #{h['mx'].to_i},#{h['my'].to_i} #{h['lx'].to_i},#{h['ly'].to_i}" } * ' '
      tempfile = Tempfile.new(['signature', '.png'])
      Open3.popen3("convert -size 698x300 xc:transparent -stroke blue -draw @- #{tempfile.path}") do |input, _output, _error|
        input.puts instructions
      end
      @record.admin_signature = tempfile
      record_params.delete 'admin_signature'
    end

    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to records_url, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to request.referer, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def deleted
    @records = PaperTrail::Version.where(event: 'destroy')
  end

  def update_field
    record = Record.find(params[:id])
    if params.key?('multi')
      params['record']['data'].each do |key, value|
        record.data[key] = value.to_json
      end
    else
      field_name = params[:field_name].gsub('record[data]', '').delete('[]')
      field_value = params[:field_value]
      record.data[field_name] = field_value
    end
    record.save
    render json: { msg: 'field updated', status: 'whatever' }
  end

  def import_csv
    file = params[:csv_file]
    total = current_user.populate_records(file.path, params[:form_id])

    respond_to do |format|
      format.html { redirect_to records_url, notice: "File was successfully parsed. (#{total} records added)" }
      format.json { head :no_content }
    end
 end

  def history
    @versions = PaperTrail::Version.order('created_at DESC')
 end

  private

  def render_record_report(record)
    send_data record.report.generate, filename: 'report.pdf',
                               type: 'application/pdf',
                               disposition: 'attachment'
  end
  
  # Use callbacks to share common setup or constraints between actions.
  def set_record
    @record = Record.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def record_params
    # params.require(:record).permit(:form_id, :data)
    params.require(:record).permit!
  end
    end

app/helpers/records_helper.rb
module RecordsHelper
  def find_version_author_name(version)
    user = User.find_version_author(version) 
    user ? user.email : ''
  end
  
  def diff(content1, content2)
   changes = Diffy::Diff.new(content1, content2, 
                             include_plus_and_minus_in_html: true, 
                             include_diff_info: true)
   changes.to_s.present? ? changes.to_s(:html).html_safe : 'No Changes'
end

end

app/views/records/_record.html.erb
hi

app/views/records/_record_preview.html.erb
    <p>
      <strong>Form:</strong>
      <%= @record.form.name %>
    </p>
    <p>
      <strong>Created_by:</strong>
      <%= @record.user.email %>
    </p>

    <%- @record.data_fields.each do |pair|%>
      <p>
      <strong><%= pair.first[0..-16] %>:</strong>
        <%= pair.last %>
      </p>
    <% end %>  
    
    <% @record.locations.each do |location| %>
      <%= location.full_address %>
    <% end %>
    <div class="row">
      <div class="col-md-4">
        <h3 class=""> User's Signature </h3>
        <%- if @record.signature.exists? %>
          <%= image_tag @record.signature, :class=> "img-thumbnail" %>
        <% else %>
          <%= image_tag "image-not-available", :class=> "img-thumbnail" %>
        <% end %>
        <%#= image_tag @record.signature, :class=> "img-thumbnail" %>
      </div>
      <div class="col-md-offset-2 col-md-4">
        <h3 class="muted"> Admin Approve Signature </h3>
        <%- if @record.admin_signature.exists? %>
          <%= image_tag @record.admin_signature ,:class=> "img-thumbnail"%>
        <% else %>
          <%= image_tag "image-not-available", :class=> "img-thumbnail" %>
        <% end %>

      </div>
    </div>

app/views/records/_sidebar.html.erb
        <div class="panel panel-default">
          <div class="panel-heading">Record created by: </div>
          <div class="panel-body">
            <% if @record.user %>
              <strong> <%= @record.user.email rescue "no user"%> </strong>
              <%= image_tag "unknown_icon.gif", :class => "media-object"%>
              <%= @record.user.plan.name %>
            <% else %>
              <h4> No data</h4>
            <% end %>
          </div>
        </div>
        
        <div class="panel panel-default">
          <div class="panel-heading">Headers: </div>
          <div class="panel-body">
            <%= @record.data.collect {|k,v| k} %>
          </div>
        </div>    
         <div class="panel panel-default">
          <div class="panel-heading">History: </div>
          <div class="panel-body">
            <%- @record.versions.each do |version| %>
              <p>  <strong><%= User.find(version.whodunnit).email %></strong> <%= version.event %> at <%= version.created_at %></p>
            <% end %>  
          </div>
        </div> 

app/views/records/_sortable_tree.html.erb
 <ol class="tree" data-rebuild-url="<%= rebuild_records_url%>">
  <%#= sortable_tree @records %>
  <%=raw sortable_tree @records, :type => :sortable, :new_url => new_record_path, :title => :title, :max_levels => 5, :rebuild_url => rebuild_records_url %>
</ol>

app/views/records/_table.html.erb
<h4  class="bg-success">Nested Records</h4>

<div class="panel panel-default">    
    <div class="panel-body">      
  <table class="table  table-condensed table-hover">
   
    <!--thead>
      <tr>
        <th>Type</th>
        <th>Id</th>
        <th>Created_at</th>
        <th colspan="2" style="width:10%;"></th>
      </tr>
    </thead-->

    <tbody>
      <% @record.children.each do |record| %>
        <tr>
          <td><strong><%= link_to "##{record.id}", edit_record_path(record), :remote=>true %> </strong></td>
          <td><strong><%= record.title rescue ''%></strong></td>
          <td><strong><%= record.form.name rescue ''%></strong></td>
          <td><%= time_ago_in_words(record.created_at)%> ago by <%= record.user.email rescue nil %> </td>
          <td style="width: 5%;"> 
            <%- if record.data %>
             <%= link_to "Report", record_path(record, format: :pdf), :class=>"btn btn-xs btn-info" %> </td>
         <% else %>
          <span class="muted"> no data </span> 
         <% end %>
           <td style="width: 5%;"><%= link_to "Edit", edit_record_path(record), :class=>"btn btn-xs btn-info" %> </td>
           <td style="width: 5%;"><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' }, :remote=>true, :class=>"btn btn-xs btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
  <div class="panel-footer">
    <div class="row">
      <div class="col-md-3">
      <%= form_tag new_record_path do %>
      <%= select_tag  'form_id', options_from_collection_for_select(Form.all, "id", "name") , :class=>"form-control input-sm" %>
    <% end %>
    </div>
    <div class="col-md-3">
    <%= link_to 'New Record', new_record_path(:parent_id => @record.id), data: { modal: true }, :class=>"go-btn btn btn-info btn-xs" %>
    </div>
  </div>
  </div>
</div>
<script>
$(function () {
  $('.go-btn').click(function() {
    var selected = $('#form_id option:selected');
    if (selected.length) {
        // Do something with your selection
        var link = $('.go-btn').attr('href');
        var finalUrl =  link + "?form_id=" + selected.val();
        $('.go-btn').attr('href', finalUrl);
    }
  });

    })
  </script>

app/views/records/_versions.html.erb
<h2>Previous Versions</h2>

<table class='table table-hoover table-striped table-condensed'>
  <thead>
    <tr>
      <th>Index</th>
      <th>Date</th>
      <th>Author</th>
      <th>Event</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%- record.versions.reverse.each do |version| %>
      <tr>
        <td><%= version.index %></td>
        <td><%= version.created_at %></td>
        <td><%= find_version_author_name(version) %></td>
        <td><%= version.event.humanize %></td>
        <td>
          <%= link_to diff_record_version_path(record, version), class: "btn btn-xs btn-success btn-trans" do %>
            <i class="fa  fa-code-fork"></i>  Diff
          <% end %>
        </td>
        <td>
          <%= link_to  rollback_record_version_path(record, version), method: 'PATCH', class: "btn btn-xs btn-warning btn-trans" do %>
            <i class="fa  fa-undo"></i>  Rollback
          <% end %>
          </td>
        
        </tr>
    <% end %>
  </tbody>
</table>

app/views/records/deleted.html.erb
<h1>Bring back records</h1>

<table class='table table-hover table table-bordered table-striped'>
  <thead>
    <tr>
      <th>ID</th>
      <th>status</th>
      <th>Deleted by</th>
      <th>At</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @records.each do |record_version| %>
      <%- record = record_version.reify %>
      <tr>
        <td><%= record.id %></td>
        <td><%= record.status %></td>
        <td><%= find_version_author_name(record_version) %></td>
        <td><%= record.created_at %></td>
        <td><%= link_to 'Bringback', bringback_version_path(record_version), method: 'PATCH', :class=> "btn btn-warning btn-sm btn-trans" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Back', records_path, :class=> "btn btn-info  btn-trans"%>

app/views/records/history.html.erb
<div class="">
  <h3>Records History</h3>

  <ul>
    <% @versions.each do |version| %>
      <li>
        <%= l(version.created_at, format: "%-d.%m.%Y %H:%M:%S %Z") %><br/>
        Made by: <%= User.find(version.whodunnit).email %>
        Event ID: <%= version.id %><br/>
        <b>Target:</b> <%= version.item_type %>
        <small>(id: <%= version.item_id %>)</small>; <b>action</b> <%= version.event %>;<br/>
        <div>
          More info:
          <pre><%= version.object %></pre>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-9">
 <div class="panel panel-success">    
  <div class="panel-heading">
    <h3 class="panel-title"> Records list </h3>
  </div>
  <div class="panel-body"> 
       <br />
       <table class="table table-hover   table-condensed table-striped">
  <thead>
    <tr>
      <th> <%= sort_link(@q, :id)%></th>
      <th> <%= sort_link(@q, :form)%></th>
      <th> <%= sort_link(@q, :author)%></th>
      <th> Progress</th>
      <th> <%= sort_link(@q, :status)%></th>
      <th> <%= sort_link(@q, :created_at)%> </th>
      <th colspan="4" style="width:10%;">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td> 
          <%= link_to  edit_record_path(record)  do %>
            <strong><span class="label label-primary"> <%= record.id %> </span></strong>
          <% end %> 
        </td>
        <td><span class="muted"><%= record.form.name rescue ''%></span></td>
        <td><%= record.user.email rescue ''%></td> 
        <td>
          <div class="progress">
            <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="min-width: 0em; width: <%= record.extras["progress"] rescue '0%'%>
;">
     <%= record.extras["progress"] rescue ''%>
  </div>
</div>
           <%#= record.extras["current_step"] rescue '' %> </td>
        <td> <%= record_status(record.status) %> </td>
        <td><%= time_ago_in_words(record.created_at)%> ago </td>
        <td> 
          <%- if record.data and record.form.template.exists? %>
            <%= link_to "Report", record_path(record, format: :pdf), :class=>"btn btn-xs  btn-info" %> </td>
          <% else %>
            <%= link_to "Report", record_path(record, format: :pdf), :disabled => true, :class=>"btn btn-xs  btn-info" %> </td>
          <% end %>
       <td>
        <%= link_to record_path(record), :class=>"btn btn-xs btn-trans btn-info" do %> 
          <i class="fa  fa-eye"></i>
        <% end %>
      </td>
        <td>
          <% if can? :edit, record %>
            <%= link_to "Wizzard", former_path(:step1, :record_id => record.id), :class=> "btn btn-xs btn-primary" %> 
            <%#= link_to "Edit", edit_record_path(record), :class=>"btn btn-xs btn-primary" %> </td>
          <% end %>
          <td>
            <% if can? :destroy, record %>
              <%= button_to  record, method: :delete, data: { confirm: 'Are you sure?'}, :class=>"btn  btn-xs btn-danger" do %>
                <i class="fa fa-trash"></i>
              <% end %>
            <% else %>
            
              <%= button_to  record, method: :delete, data: { confirm: 'Are you sure?' }, :disabled => true, :class=>"btn disabled btn-xs btn-danger" do %>
                <i class="fa fa-trash"></i>
              <% end %>
            <% end %>
         </td>
      </tr>
    <% end %>
  </tbody>
</table> 
    </div>
  <div class="panel-footer">
    <%#= link_to 'New Record', new_record_path, data: { modal: true }, :class=>"btn btn-primary" %>
    <%= link_to 'See Deleted Records', deleted_records_path, :class=> "btn btn-success btn-trans" %>
  </div>
</div>

 
  </div>
  <div class="col-md-3">
   <div class="panel panel-success">    
    <div class="panel-heading">
      <h3 class="panel-title"> Search form </h3>
    </div>
    <div class="panel-body"> 
      <%= search_form_for @q do |f| %>
    <%= f.label :title %>
    <%= f.search_field :title_cont , :class=> "form-control"%>

    <%= f.label :author_email %>
    <%= f.search_field :user_email_cont, :class=> "form-control" %>

    <%= f.label :form %>
    <%= f.search_field :form_name_cont, :class=> "form-control" %>
    
    <%#= f.label :name_or_description_or_email_or_articles_title_cont %>
    <%#= f.search_field :name_or_description_or_email_or_articles_title_cont %>
    <br>
    <%= f.submit "Search", :class=> "btn btn-info btn-block"%>
  <% end %>
  </div>
</div>  
 <div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Records Import:</h3>
  </div>
  <div class="panel-body">
    <%= form_tag(import_csv_path, multipart: true, :class => "form-inline") do %>
      <div class="form-group">
        <%= file_field_tag :csv_file, :class => "form-control", required: true %>
        <span id="helpBlock" class="help-block">*file should have column headers</span>
      </div>
      <div class="form-group">
        <%= select_tag "form_id", options_from_collection_for_select(Form.all, "id", "name") , :class => "form-control"%>
        <span id="helpBlock" class="help-block">*fields should be equal to headers</span>
      </div>  
        <%= submit_tag 'Click to process', :class => " btn btn-info btn-block"%>
    <% end %>
  </div>
</div>
 
  </div>

</div>

   

app/views/records/manage.html.haml
%div.panel.panel-success
  %div.panel-heading
    %h3.panel-title  Records Manage Page
  %div.panel-body
    %hr
    %ol.sortable_tree{ :data => { :max_levels => 3, :rebuild_url => rebuild_records_url } }
      = build_server_tree @records, :type => :sortable
    %p= link_to "Go back to records", records_path, :class=>"btn btn-info"

app/views/records/new.html.erb
<h3>New Record</h3>

<%= render 'form' %>

<%#= link_to 'Back', records_path %>

app/views/records/show.html.erb
<%= content_for :head do %>
  <script>
    $(document).ready(function(){           
     $('.signature_form').signaturePad({ drawOnly: true, lineTop: 190, validateFields: false})
  });
  </script>
<% end %>

<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success">    
      <div class="panel-heading">
        <h3 class="panel-title"><strong>#<%= @record.id %> <%= record_status(@record.status)%></strong></h3>
      </div>
      <div class="panel-body">   
        <%= render "record_preview"%>       
        <% if @record.status == "awaiting"%>
        <h3 class="bg-danger">Admin Section! </h3>
        <div class="">
          <%= nested_form_for(@record,  :html => {:multipart => true, :class=>"signature_form" }, role: "form") do |f| %>
            <% if @record.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>
                <ul>
                <% @record.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <hr>
            <%= f.hidden_field :form_id %>
            <%= f.hidden_field :id %>
            <%#= f.select :status, options_for_select(Record::RECORD_STATUSES)%>

            <div class="form-group ">
              <%= f.label :status %>
              <div class="row">
                <div class="col-xs-12">
                  <%= f.select :status, Record::RECORD_STATUSES.collect {|d| [d.to_s,d.to_s]}, :class=>"form-control" %>
                </div>
              </div>
            </div>
            <div class= "well sig sigWrapper">
              <canvas class= "pad" width="698" height="300">
                <%= f.hidden_field :admin_signature, :value => nil, :class => 'output' %>
              </canvas>
            </div>
        
            <ul class="sigNav">
              <li class="clearButton"><a href="#clear" class="btn btn-default btn-Clear">Clear Signature Pad</a></li>
            </ul>
            <div class="">
              <%= f.submit "Approve", :class=>"btn btn-sm btn-primary" %>
            </div>
          <% end %>

        </div>
      <% end %>
      </div>
      <div class="panel-footer">
        <%= link_to 'Edit', edit_record_path(@record), :class => "btn btn-info" %> 
        <%= link_to 'Back', records_path , :class => "btn btn-danger"%>
      </div>
    </div>
    <hr>
  </div>
</div>
<div class="well">
  <%= render 'records/versions', record: @record %>
</div>