config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Booker::Application.routes.draw do  
  resources :images
  resources :supplements
  mount Payola::Engine => '/payola', as: :payola
  
  default_url_options :host => "lvh.me:3000"
 # default_url_options :host => "sshrsa.com:3000"
  resources :steps
  get '/records/history', to: 'records#history', as: :records_history
  #resources :records
  resources :versions, only: [] do
    member do
      patch :bringback  # <= and that
    end
  end
  
  resources :records do
    collection do 
      get :deleted # <= this
    end
    member do
     get :update_field, to: 'records#update_field' 
    end
    
    resources :versions, only: [:destroy] do
      member do
        get :diff, to: 'versions#diff'
        patch :rollback, to: 'versions#rollback'
      end
    end

    collection do
      get   :manage
      get   :drafts
      get   :awaiting_approvement
      get   :approved
      get   :approvement_request
      get   :accept_approvement
      get   :cancel_approvement
      # required for Sortable GUI server side actions
      post :rebuild
    end
  end
  resources :inputs
  resources :attachments
  resources :forms
  resources :former
  get "home", to: "pages#home", as: "home"  
  match "create_record", to: "records#create_record", as: "create_record", via: [:get, :post]
  match "import_csv", to: "records#import_csv", as: "import_csv", via: [:post]
  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  constraints(SubdomainPresent) do    
    root "pages#inside", as: :dashboard
    get "inside", to: "pages#inside", as: "inside"    
    get "activity", to: "pages#activity", as: "activity"    
    
    post 'qrc/disable_otp'
    post 'qrc/enable_otp'

    namespace :admin do
      root "base#index"
      post "users/invite_user", as: 'invite_user'
      resources :users
      get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
      get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
      get "forms/dashboard", to: "forms#dashboard", as: "forms_dashboard"
      resources :posts
      resources :forms
      resources :inputs      
    end
  end

  constraints(SubdomainBlank) do
    post 'pages/require_subdomain'
    root "pages#home"
    resources :accounts, only: [:new, :create]
  end

end

app/controllers/admin/forms_controller.rb
class Admin::FormsController < Admin::BaseController
  protect_from_forgery with: :null_session, if: proc { |c| c.request.format == 'application/json' }
  respond_to :html, :json
  before_action :set_form, only: [
    :edit,
    :update,
    :destroy,
    :show
  ]

  def dashboard
    @published_form_count = Form.count
  end

  def index
    # @forms = Form.where('account_id=?', current_account.id).page(params[:page]).per(50)
    @q = Form.where('account_id=?', current_account.id).ransack(params[:q])
    @forms = @q.result.page(params[:page])
    # @forms = Form.page(params[:page]).per(50)
  end

  def drafts
    @forms = Form.page(params[:page]).per(50)
  end

  def new
    @form = Form.new
    respond_modal_with @form
  end
  
  def show
    respond_to do |format|
      format.tlf { render_sample_tlf(@form) }
    end
  end

  def create
    @form = Form.new(form_params)
    @form.account = current_account
    @form.save
    respond_modal_with @form, location: admin_forms_path
  end

  def edit
  end

  def update
    
    @form.slug = nil
    if @form.update(form_params)
      binding.pry
      redirect_to admin_forms_path, notice: 'Form successfully edited.'
    else
      flash[:alert] = 'The form was not edited.'
      render :edit
    end
  end

  def destroy
    @form.destroy
    redirect_to admin_forms_path, notice: 'The form has been deleted.'
  end

  private

  def set_form
    @form = Form.friendly.find(params[:id])
    redirect_to action: 'index' if @form.account_id != current_account.id
  end
  
  def render_sample_tlf(form)
    send_data File.read(form.sample_layout), filename: 'sample.tlf',
                               type: 'application/tlf',
                               disposition: 'attachment'
  end

  def form_params
    params.require(:form).permit!
    # params.require(:form).permit(
    # :name,
    # :description,
    # :content_md,
    # :draft,
    # :updated_at,
    # inputs_attributes: [:id, :name, :description, :required, :_destroy],
    # steps_attributes: [:id, :title, :description, :number, :_destroy]
    # )
  end
end

app/views/admin/forms/_field_value_fields.html.erb
<div class="form-group form-group-sm">
  <div class="row">
    <div class="col-xs-3 col-xs-offset-3">
      <%= f.text_field :value, class: "form-control monospaced-control"%>
    </div>
    <div class="col-xs-6">
      <%= f.link_to_remove(:class=>"btn  btn-sm btn-danger btn-trans") do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
  </div>  
</div>

app/views/admin/forms/_form.html.erb
<%= nested_form_for([:admin,@form], remote: request.xhr?, :html => { data: { modal: true }}, role: "form") do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group ">
  <%= f.label :name %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.text_field :name, :autofocus => true, class: "form-control monospaced-control", placeholder: "Title (also used for URL slug)..." %>
    </div>
  </div>
</div>
<div class="form-group input-group-sm">
  <%= f.label :description %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.text_field :description,  class: "form-control monospaced-control", placeholder: "Title (also used for URL slug)..." %>
    </div>
  </div>
</div>
<div class="form-group form-group-sm">
  <div class="row">
    <div class="col-xs-12">
      <div class="checkbox">
      <label>
        <%= f.check_box :file_upload,  class: " " %> Enable file upload
      </label>  
      </div>
    </div>
  </div>
</div>

<div class="form-group form-group-sm">
  <div class="row">
    <div class="col-xs-12">
      <div class="checkbox">
      <label>
        <%= f.check_box :signature_required,  class: " " %> Signature Required
      </label>  
      </div>
    </div>
  </div>
</div>
<div class="form-group form-group-sm">
  <div class="row">
    <div class="col-xs-12 checkbox">
      <label>
        <%= f.check_box :admin_signature_required,  class: " " %> Admin Signature Required
      </label>
    </div>
  </div>
</div>
<div class="form-group form-group-sm">
  <div class="row">
    <div class="col-xs-12">
      <%= f.label :template %>
      <p><%= @form.template.exists? ? link_to(@form.template_file_name, "#{@form.template.url}?dl=1") : "-" %></p>
      <%= f.file_field :template,  class: " " %>
    </div>
  </div>
</div>


<h4>Form Steps</h4>
<hr>
<%= f.fields_for :steps %>
<p>
  <%= f.link_to_add(:steps, :class=>'btn btn btn-info ') do %>
    <i class="fa  fa-plus-circle"></i> add step
  <% end %>
</p>
<div class="row">
  <div class="col-xs-12 padded">
    <button class='btn btn-primary'>
      <i class='fa fa-plus-square'></i> Save
    </button> - <%= link_to "Cancel", admin_forms_path, :class=>"btn btn-default" %>
  </div>
</div>

<% end %>

app/views/admin/forms/_input_fields.html.erb
<div class="form-group form-group-sm button_to input_section">
  <div class="row">
    
      <p class="text-info"><strong>friendly-id: <%= f.object.slug %></strong> </p>
    <div class="col-xs-3">
      <%= f.text_field :name, class: "form-control monospaced-control"%>
    </div>
    <div class="col-xs-2">
        <%#= f.text_field :name, class: "form-control monospaced-control"%>
        <%= f.select "control", Input::CONTROL_TYPES.map{|type| [ type['name'], type['value'] ] }, { :include_blank => "Please Select..." , :class=>"input_select form-control"} ,:class=>"form-control  input_select"%>
    </div>
    <div class="col-xs-3">
      <%= f.label :required %>
      <%= f.check_box :required %>
    </div>
    <div class="col-xs-3">
      <%= f.text_area :help, class: "form-control monospaced-control"%>
    </div>
    <div class="col-xs-1">  
      <%#= f.link_to_remove "Del", :class=>"btn btn-xs  btn-warning" %>
      <%= f.link_to_remove(:class=>"btn  btn-sm btn-danger btn-trans") do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
  </div>  
  <hr>
  <span class="field_relation_section ">
    <div class="row">
      <div class="col-xs-offset-2 col-xs-3">
        <%= f.simple_fields_for :data, OpenStruct.new(f.object.data) do |p| %>
          <%= p.label "Choose related type"%>
          <%= p.select :relation, Form.all.map {|f| [f.name, f.id] }, { :class=> "  form-control"}, :class => "form-control" %>
        <% end %>
      </div>
    </div>
  </span>
  <span class="field_values_section">
  <%= f.fields_for :field_values  %>
  <div class="row"> 
    <div class="col-xs-8 col-xs-offset-2">
      <p>
        <%= f.link_to_add(:field_values, :class=>'btn btn-xs btn-warning btn-trans') do %>
          <i class="fa  fa-plus-circle"></i> add field value
        <% end %>
      </p>
    </div>
  </div>
</div>
<script> 
$( document ).ready(function() {
  $('.input_select').each(function( index ) {
  var selected_input =  $( this ).val();
   switch(selected_input)
  {
    case "dropdown":
    case "checkboxes":
    case "tags":
    case "radio":
      $(this).closest('.input_section').find('.field_relation_section').fadeOut('fast');
      $(this).closest('.input_section').find('.field_values_section').fadeIn('fast');
    break;
    case 'relation':
      $(this).closest('.input_section').find('.field_values_section').fadeOut('fast');
      $(this).closest('.input_section').find('.field_relation_section').fadeIn('fast');
    break;
    default:
      $(this).closest('.input_section').find('.field_values_section').fadeOut('fast');
      $(this).closest('.input_section').find('.field_relation_section').fadeOut('fast');
      break;

 }
});
  $(".input_select").change(function() {
    var n = $(this).val();
    switch(n)
  {
    case "text_field":
    case "text_area":
    case "phone":
    case "email":
      $(this).closest('.input_section').find('.field_values_section').fadeOut('fast');
      $(this).closest('.input_section').find('.field_relation_section').fadeOut('fast');
      break;
    case 'relation':
      $(this).closest('.input_section').find('.field_values_section').fadeOut('fast');
      $(this).closest('.input_section').find('.field_relation_section').fadeIn('fast');
    break;
    default:
      $(this).closest('.input_section').find('.field_relation_section').fadeOut('fast');
      $(this).closest('.input_section').find('.field_values_section').fadeIn('fast');
    break;
 }
});
});

</script>

app/views/admin/forms/_slave_form_fields.html.erb
<div class="form-group form-group-sm well">
  <div class="row">
    <div class="col-xs-3">
      <%= f.text_field :name, class: "form-control monospaced-control"%>
    </div>
    <div class="col-xs-3">
      <%= f.link_to_remove(:class=>"btn  btn-sm btn-danger btn-trans") do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-xs-offset-1 col-xs-11">
      <%= f.fields_for :inputs  %>
      <p>
        <%= f.link_to_add(:inputs, :class=>'btn btn-xs btn-success btn-trans ') do %>
          <i class="fa  fa-plus-circle"></i> add input
        <% end %>
      </p>

    </div>
  </div>

</div>

app/views/admin/forms/_step_fields.html.erb
 <div class="form-group form-group-sm">
    <div class="row">
      <div class="col-xs-3">
        <%= f.number_field :number, class: "form-control monospaced-control"%>
      </div>
      <div class="col-xs-6">
        <%= f.text_field :title, class: "form-control "%>
      </div>
      <div class="col-xs-3">
        <%= f.link_to_remove(:class=>"btn  btn-sm btn-danger btn-trans") do %>
          <i class="fa fa-trash"></i>
        <% end %>
      </div>
    </div>  <!-- /row -->
   
    <div class="row">
      <div class="col-xs-offset-1 col-xs-11">
        <h4 class="text-info"> Modals </h4>
        <hr>
        <div >
          <%= f.fields_for :slave_forms %>
        </div>
        <p>
        <%= f.link_to_add(:slave_forms, :class=>'btn btn-sm btn-trans btn-success ') do %>
          <i class="fa  fa-plus-circle"></i> add nested form
        <% end %>
      </p>

      </div>
    </div>
 
    <div class="row">
      <div class="col-xs-offset-1 col-xs-11">
        <h4 class="text-info"> Inputs </h4>
        <hr>
        <%= f.fields_for :inputs  %>
        <p>
        <%= f.link_to_add(:inputs, :class=>'btn btn-sm btn-trans btn-success ') do %>
          <i class="fa  fa-plus-circle"></i> add input
        <% end %>
      </p>
      </div>
    </div>
  
  </div>

app/views/admin/forms/edit.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Editing Form</h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  </div>
<%#= link_to 'Show', @form %> 
<%#= link_to 'Back', forms_path %>

app/views/admin/forms/index.html.erb
<p id="notice"><%= notice %></p>


<div class="col-md-9">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Forms</h3>
    </div>
    <div class="panel-body">
      <table class="table table-hover table  table-striped">
        <thead>
          <tr>
            <th><%= sort_link(@q, :title)%></th>
            <th> PDF Template</th>
            <th> <%= sort_link(@q, :description)%></th>
            <th> <%= sort_link(@q, :created_at)%> </th>
            <th colspan="3" style="width:10%;"></th>
          </tr>
        </thead>
        <tbody>
          <% @forms.each do |form| %>
            <tr>
              <td><strong><%= link_to form.name, edit_admin_form_path(form), :class =>"" %></strong></td>
              <td><%= form.template.exists? ? link_to(form.template_file_name, "#{form.template.url}?dl=1") : "-" %></td>
              <td><%= form.description %></td>
              <td><%= time_ago_in_words(form.created_at)%> ago </td>
              <td><%= link_to 'sample.tlf', admin_form_path(form, :format => :tlf) , :class =>"btn btn-xs btn-trans btn"%> </td>
              <td><%= link_to 'Edit', edit_admin_form_path(form) , :class =>"btn btn-xs btn-success btn-trans"%> </td>
              <td><%= button_to 'Destroy', admin_form_path(form), method: :delete, data: { confirm: 'Are you sure?' } ,:class =>"btn btn-xs btn-danger"%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <hr>
      <%= link_to 'New Form', new_admin_form_path, data: { modal: true }, :class=>"btn btn-trans btn-success " %>
    </div>
  </div>
</div>

<div class="col-md-3">
   <div class="panel panel-success">    
    <div class="panel-heading">
      <h3 class="panel-title"> Search form </h3>
    </div>
    <div class="panel-body"> 
      <%= search_form_for [:admin,@q] do |f| %>
    <%= f.label :name %>
    <%= f.search_field :name_cont , :class=> "form-control"%>
    
    <%= f.label :description %>
    <%= f.search_field :description_cont , :class=> "form-control"%>
    <%#= f.label :name_or_description_or_email_or_articles_title_cont %>
    <%#= f.search_field :name_or_description_or_email_or_articles_title_cont %>
    <br>
    <%= f.submit "Search", :class=> "btn btn-info btn-block"%>
  <% end %>
  </div>
</div>  

app/views/admin/forms/new.html.erb
<h3>New Form</h3>

<%= render 'form' %>

<%= link_to 'Back', admin_forms_path %>

app/views/admin/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @form.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @form.description %>
</p>

<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>